### ISSUE TITLE
Views Database

### ISSUE THREAD

**Issue by EmilyRosenfeld** [marcosdayanm/Ship_Invasion#21]
Crear las Views del esquema para ejecutar las querries de "Select" con mayor consistencia y eficiencia

Nombre del caso de Uso
Crear las vistas de la base de datos

Requerimientos Relacionados
Requerimiento 1: Crear esquema de bases de datos
Requerimiento 4: API Endpoints para datos de DB

Objetivo en Contexto
Crear vistas para que sea más fácil y eficiente hacer consultas desde la API

Condiciones previas
Tener el esquema, tablas, relaciones y restricciones creadas

Condición del Sistema si el caso de uso se ejecuta exitosamente
La API puede hacer las consultas necesarias a las vistas y éstas funcionan de manera consistente y coherente

Condición del Sistema si el caso de uso falla
Las vistas tienen inconsistencias y la API no puede acceder a toda la información de las tablas del esquema

Actores principales que participan en el caso de uso
Arquitecto de bases de datos, cliente conexión de la API

Actores adicionales en la ejecución del caso de uso
Sistema gestor de bases de datos

Evento que desencadena la ejecución del caso de uso
Una consulta a las vistas de la base de datos a través de un endpoint de la API

Flujo principal del caso de uso
Se realiza una consulta desse un endpoint de la API a la vista y el servidor de la base de datos regresa la información solicitada

Pasos alternativos al Flujo Principal
Monitoreo de la consistencia de las vistas, generación de vistas adicionales y actualización de la información de las vistas

**Comment by marcosdayanm** [comment]
Nombre del caso de Uso
Crear las vistas de la base de datos

Requerimientos Relacionados
Requerimiento 1: Crear esquema de bases de datos
Requerimiento 4: API Endpoints para datos de DB

Objetivo en Contexto
Crear vistas para que sea más fácil y eficiente hacer consultas desde la API

Condiciones previas
Tener el esquema, tablas, relaciones y restricciones creadas

Condición del Sistema si el caso de uso se ejecuta exitosamente
La API puede hacer las consultas necesarias a las vistas y éstas funcionan de manera consistente y coherente

Condición del Sistema si el caso de uso falla
Las vistas tienen inconsistencias y la API no puede acceder a toda la información de las tablas del esquema

Actores principales que participan en el caso de uso
Arquitecto de bases de datos, cliente conexión de la API

Actores adicionales en la ejecución del caso de uso
Sistema gestor de bases de datos

Evento que desencadena la ejecución del caso de uso
Una consulta a las vistas de la base de datos a través de un endpoint de la API

Flujo principal del caso de uso
Se realiza una consulta desse un endpoint de la API a la vista y el servidor de la base de datos regresa la información solicitada

Pasos alternativos al Flujo Principal
Monitoreo de la consistencia de las vistas, generación de vistas adicionales y actualización de la información de las vistas
