### ISSUE TITLE
Diagramas UML

### ISSUE THREAD

**Issue by EmilyRosenfeld** [marcosdayanm/Ship_Invasion#22]
Nombre del caso de Uso
Actualización de diagramas UML

Requerimientos Relacionados
Todos

Objetivo en Contexto
Llevar un registro y tangibilizar los diferentes procesos que ocurren en la arquitectura del proyecto y los pin cápales actores relacionados a ellos

Condiciones previas
Llevar a cabo una planeación adecuada de los diferentes procesos del proyecto para que se puedan tangibilizar

Condición del Sistema si el caso de uso se ejecuta exitosamente
Los diagramas UML son actualizados correctamente al inicio de cada sprint y se registran todos los procesos y servicios que serán desarrollados

Condición del Sistema si el caso de uso falla
No se lleva un registro adecuado de todos los procesos y desarrollos del sprint y se da cabida a errores de planeación
Actores principales que participan en el caso de uso
Desarrolladores, SCRUM master

Actores adicionales en la ejecución del caso de uso
En este caso no hay actores adicionales

Evento que desencadena la ejecución del caso de uso
El paso al siguiente sprint y la planeación de la ejecución de los siguientes requerimientos

Flujo principal del caso de uso
Se junta el equipo de desarrollo a pensar y planear en las implicaciones de los requerimientos venideros y se actualizan los diagramas UML

Pasos alternativos al Flujo Principal
Se piensa en requerimientos adicionales y en el desarme de requerimientos innecesarios

**Comment by marcosdayanm** [comment]
Nombre del caso de Uso
Actualización de diagramas UML

Requerimientos Relacionados
Todos

Objetivo en Contexto
Llevar un registro y tangibilizar los diferentes procesos que ocurren en la arquitectura del proyecto y los pin cápales actores relacionados a ellos

Condiciones previas
Llevar a cabo una planeación adecuada de los diferentes procesos del proyecto para que se puedan tangibilizar

Condición del Sistema si el caso de uso se ejecuta exitosamente
Los diagramas UML son actualizados correctamente al inicio de cada sprint y se registran todos los procesos y servicios que serán desarrollados

Condición del Sistema si el caso de uso falla
No se lleva un registro adecuado de todos los procesos y desarrollos del sprint y se da cabida a errores de planeación
Actores principales que participan en el caso de uso
Desarrolladores, SCRUM master

Actores adicionales en la ejecución del caso de uso
En este caso no hay actores adicionales

Evento que desencadena la ejecución del caso de uso
El paso al siguiente sprint y la planeación de la ejecución de los siguientes requerimientos

Flujo principal del caso de uso
Se junta el equipo de desarrollo a pensar y planear en las implicaciones de los requerimientos venideros y se actualizan los diagramas UML

Pasos alternativos al Flujo Principal
Se piensa en requerimientos adicionales y en el desarme de requerimientos innecesarios
