### ISSUE TITLE
API Endpoints para datos de DB

### ISSUE THREAD

**Issue by EmilyRosenfeld** [marcosdayanm/Ship_Invasion#23]
Crear la API en Express.js que va a comunicarse con la base de datos para recibir los datos y mandarlos a Unity, además de mandarle datos para la inserción, la cual tendrá diferentes endpoints para satisfacer las necesidades del flujo de los datos entre la base de datos y Unity.

Nombre del caso de Uso
Desarrollo de endpoints de la API para consultas al esquema

Requerimientos Relacionados
Requerimiento 1: Crear esquema de bases de datos
Requerimiento 2: Vistas de la base de datos
Requerimiento 5: API Endpoints para Web
Requerimiento 6: Probar la API con datos dummy

Objetivo en Contexto
Desarrollar los endpoints de la API que hará consultas a las vistas del esquema con el objetivo de realizar operaciones CRUD en el esquema

Condiciones previas
Tener el esquema y las vistas completo para que pueda responder a las consultas de la API

Condición del Sistema si el caso de uso se ejecuta exitosamente
La API hace consultas a las vistas del esquema y el esquema le regresa exitosamente los datos de la consulta

Condición del Sistema si el caso de uso falla
La API presenta errores al conectarse al esquema o la API no puede manejar correctamente el formato de los datos respondidos por el esquema

Actores principales que participan en el caso de uso
Sistema gestor de base de datos, Desarrollador de la API, Unity

Actores adicionales en la ejecución del caso de uso
Arquitecto de Base de Datos

Evento que desencadena la ejecución del caso de uso
Diferentes triggers a las funciones de los endpoints de la API por procesos automáticos del flujo del videojuego o por la interacción del usuario con la UI

Flujo principal del caso de uso
Se dispara una función de la API, la API hace una consulta a la base de datos y se regresan los datos de la consulta

Pasos alternativos al Flujo Principal
Desarrollo de endpoints adicionales de la API, y constante testo y manejo de excepciones

**Comment by marcosdayanm** [comment]
Nombre del caso de Uso
Desarrollo de endpoints de la API para consultas al esquema

Requerimientos Relacionados
Requerimiento 1: Crear esquema de bases de datos
Requerimiento 2: Vistas de la base de datos
Requerimiento 5: API Endpoints para Web
Requerimiento 6: Probar la API con datos dummy

Objetivo en Contexto
Desarrollar los endpoints de la API que hará consultas a las vistas del esquema con el objetivo de realizar operaciones CRUD en el esquema

Condiciones previas
Tener el esquema y las vistas completo para que pueda responder a las consultas de la API

Condición del Sistema si el caso de uso se ejecuta exitosamente
La API hace consultas a las vistas del esquema y el esquema le regresa exitosamente los datos de la consulta

Condición del Sistema si el caso de uso falla
La API presenta errores al conectarse al esquema o la API no puede manejar correctamente el formato de los datos respondidos por el esquema

Actores principales que participan en el caso de uso
Sistema gestor de base de datos, Desarrollador de la API, Unity

Actores adicionales en la ejecución del caso de uso
Arquitecto de Base de Datos

Evento que desencadena la ejecución del caso de uso
Diferentes triggers a las funciones de los endpoints de la API por procesos automáticos del flujo del videojuego o por la interacción del usuario con la UI

Flujo principal del caso de uso
Se dispara una función de la API, la API hace una consulta a la base de datos y se regresan los datos de la consulta

Pasos alternativos al Flujo Principal
Desarrollo de endpoints adicionales de la API, y constante testo y manejo de excepciones
