### ISSUE TITLE
Probar la API con datos dummy

### ISSUE THREAD

**Issue by EmilyRosenfeld** [marcosdayanm/Ship_Invasion#25]
Generar datos dummy e insertarlos a la base de datos de MySQL a través de la API para probar que esta funcione correctamente.

Nombre del caso de Uso
Testero de los endpoints de la API con datos dummy

Requerimientos Relacionados
Requerimiento 1: Crear esquema de bases de datos
Requerimiento 2: Vistas de la base de datos
Requerimiento 4: API Endpoints para datos de DB
Requerimiento 5: API Endpoints para Web

Objetivo en Contexto
Crear tests para todos los endpoints y todos los posibles flujos de la API

Condiciones previas
Tener los endpoints de la API listos

Condición del Sistema si el caso de uso se ejecuta exitosamente
Todos los endpoints de la Ali pasan los tests de manera exitosa

Condición del Sistema si el caso de uso falla
Uno o mas endpoints de la API no pasan los tests

Actores principales que participan en el caso de uso
Desarrollador de la API, Servidor de la API

Actores adicionales en la ejecución del caso de uso
Sistema gestor de base de datos

Evento que desencadena la ejecución del caso de uso
La ejecución de los tests por parte de los desarrolladores

Flujo principal del caso de uso
Se ejecutan los tests y se muestran los resultados de los tests en cada endpoint de la API

Pasos alternativos al Flujo Principal
El desarrollo de más tests para cada endpoint

**Comment by marcosdayanm** [comment]
Nombre del caso de Uso
Testero de los endpoints de la API con datos dummy

Requerimientos Relacionados
Requerimiento 1: Crear esquema de bases de datos
Requerimiento 2: Vistas de la base de datos
Requerimiento 4: API Endpoints para datos de DB
Requerimiento 5: API Endpoints para Web



Objetivo en Contexto
Crear tests para todos los endpoints y todos los posibles flujos de la API

Condiciones previas
Tener los endpoints de la API listos

Condición del Sistema si el caso de uso se ejecuta exitosamente
Todos los endpoints de la Ali pasan los tests de manera exitosa

Condición del Sistema si el caso de uso falla
Uno o mas endpoints de la API no pasan los tests

Actores principales que participan en el caso de uso
Desarrollador de la API, Servidor de la API

Actores adicionales en la ejecución del caso de uso
Sistema gestor de base de datos

Evento que desencadena la ejecución del caso de uso
La ejecución de los tests por parte de los desarrolladores

Flujo principal del caso de uso
Se ejecutan los tests y se muestran los resultados de los tests en cada endpoint de la API

Pasos alternativos al Flujo Principal
El desarrollo de más tests para cada endpoint
