### ISSUE TITLE
Pantalla de Inicio

### ISSUE THREAD

**Issue by EmilyRosenfeld** [marcosdayanm/Ship_Invasion#26]
Desarrollar una pantalla de inicio intuitiva y visualmente atractiva que facilite la navegación por las opciones del juego, incluyendo el acceso al menú y créditos.

Nombre del caso de Uso
Desarrollo de pantalla de inicio para videojuego

Requerimientos Relacionados
Requerimiento 15: Lógica de C# para todos los GameObjects

Objetivo en Contexto
Desarrollo de pantalla de títulos intuitiva y atractiva para que los usuarios puedan acceder al menú del juego, a las configuraciones y a los créditos

Condiciones previas
Tener algunos endpoints de la base de datos de la API

Condición del Sistema si el caso de uso se ejecuta exitosamente
La pantalla de inicio es atractiva y todos los botones funcionan de manera exitosa

Condición del Sistema si el caso de uso falla
La pantalla de inicio presenta fallas y errores

Actores principales que participan en el caso de uso
El cliente, la API

Actores adicionales en la ejecución del caso de uso
Sistema gestor de base de datos

Evento que desencadena la ejecución del caso de uso
La carga de la web app que da pie a la inicialización del videojuego

Flujo principal del caso de uso
El cliente entra a la web app en donde está hosteado el videojuego y se inicializa su ejecución mostrando esa pantalla

Pasos alternativos al Flujo Principal
No aplica en este caso

**Comment by marcosdayanm** [comment]
Nombre del caso de Uso
Desarrollo de pantalla de inicio para videojuego

Requerimientos Relacionados
Requerimiento 15: Lógica de C# para todos los GameObjects

Objetivo en Contexto
Desarrollo de pantalla de títulos intuitiva y atractiva para que los usuarios puedan acceder al menú del juego, a las configuraciones y a los créditos

Condiciones previas
Tener algunos endpoints de la base de datos de la API


Condición del Sistema si el caso de uso se ejecuta exitosamente
La pantalla de inicio es atractiva y todos los botones funcionan de manera exitosa

Condición del Sistema si el caso de uso falla
La pantalla de inicio presenta fallas y errores

Actores principales que participan en el caso de uso
El cliente, la API

Actores adicionales en la ejecución del caso de uso
Sistema gestor de base de datos

Evento que desencadena la ejecución del caso de uso
La carga de la web app que da pie a la inicialización del videojuego

Flujo principal del caso de uso
El cliente entra a la web app en donde está hosteado el videojuego y se inicializa su ejecución mostrando esa pantalla

Pasos alternativos al Flujo Principal
No aplica en este caso
