### ISSUE TITLE
Definir por completo las cartas

### ISSUE THREAD

**Issue by EmilyRosenfeld** [marcosdayanm/Ship_Invasion#27]
Definir el diseño completo de cada una de las cartas, con su información correspondiente como poder de ataque, de defensa, nombre, y todas sus demás características.

Nombre del caso de Uso
Definir a la totalidad todas las características de las cartas

Requerimientos Relacionados
Requerimiento 2: Vistas de la base de datos
Requerimiento 4: API Endpoints para datos de DB
Requerimiento 10: Menú de Visualización de Cartas

Objetivo en Contexto
Definir completamente las características tanto técnicas como de diseño de las cartas para que se pueda llevar a cabo su inserción en la base de datos y su interacción

Condiciones previas
Tener completamente el planteamiento de las mecánicas del videojuego

Condición del Sistema si el caso de uso se ejecuta exitosamente
Las cartas son definidas técnica y artísticamente y están correctamente balanceadas

Condición del Sistema si el caso de uso falla
No se llega a una completa definición de las cartas y presentan inconsistencias

Actores principales que participan en el caso de uso
Cliente, Diseñadores, API

Actores adicionales en la ejecución del caso de uso
Interfaz gráfica

Evento que desencadena la ejecución del caso de uso
Juntas y reuniones por parte del equipo de desarrollo

Flujo principal del caso de uso
Se planean las características de las cartas y se lleva a cabo su diseño

Pasos alternativos al Flujo Principal
Se planean de nuevo las características de las cartas y se lleva a cabo su rediseño

**Comment by marcosdayanm** [comment]
Nombre del caso de Uso
Definir a la totalidad todas las características de las cartas

Requerimientos Relacionados
Requerimiento 2: Vistas de la base de datos
Requerimiento 4: API Endpoints para datos de DB
Requerimiento 10: Menú de Visualización de Cartas

Objetivo en Contexto
Definir completamente las características tanto técnicas como de diseño de las cartas para que se pueda llevar a cabo su inserción en la base de datos y su interacción

Condiciones previas
Tener completamente el planteamiento de las mecánicas del videojuego

Condición del Sistema si el caso de uso se ejecuta exitosamente
Las cartas son definidas técnica y artísticamente y están correctamente balanceadas

Condición del Sistema si el caso de uso falla
No se llega a una completa definición de las cartas y presentan inconsistencias

Actores principales que participan en el caso de uso
Cliente, Diseñadores, API

Actores adicionales en la ejecución del caso de uso
Interfaz gráfica

Evento que desencadena la ejecución del caso de uso
Juntas y reuniones por parte del equipo de desarrollo

Flujo principal del caso de uso
Se planean las características de las cartas y se lleva a cabo su diseño

Pasos alternativos al Flujo Principal
Se planean de nuevo las características de las cartas y se lleva a cabo su rediseño
